# Generated by Django 4.0.2 on 2022-02-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('type1', models.CharField(choices=[('GRASS', 'GRASS'), ('FIRE', 'Fire'), ('POISON', 'Poison'), ('WATER', 'Water'), ('NORMAL', 'Normal'), ('ELECTRIC', 'Electric'), ('ICE', 'Ice'), ('FIGHTING', 'Fighting'), ('GROUND', 'Ground'), ('FLYING', 'Flying'), ('PSYCHIC', 'Psychic'), ('BUG', 'Bug'), ('ROCK', 'Rock'), ('GHOST', 'Ghost'), ('DARK', 'Dark'), ('DRAGON', 'Dragon'), ('STEEL', 'Steel'), ('FAIRY', 'Fairy')], max_length=10)),
                ('type2', models.CharField(blank=True, choices=[('GRASS', 'GRASS'), ('FIRE', 'Fire'), ('POISON', 'Poison'), ('WATER', 'Water'), ('NORMAL', 'Normal'), ('ELECTRIC', 'Electric'), ('ICE', 'Ice'), ('FIGHTING', 'Fighting'), ('GROUND', 'Ground'), ('FLYING', 'Flying'), ('PSYCHIC', 'Psychic'), ('BUG', 'Bug'), ('ROCK', 'Rock'), ('GHOST', 'Ghost'), ('DARK', 'Dark'), ('DRAGON', 'Dragon'), ('STEEL', 'Steel'), ('FAIRY', 'Fairy')], max_length=10, null=True)),
                ('photo', models.ImageField(upload_to='pokemon')),
                ('moves', models.ManyToManyField(related_name='pokemon', to='pokemon.PokemonMove')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
