# Generated by Django 4.0.2 on 2022-02-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['name'], 'verbose_name_plural': 'Pokemon'},
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='photo',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='photo_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
