# Generated by Django 4.0.2 on 2022-02-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_options_remove_pokemon_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type1',
            field=models.CharField(choices=[('GRASS', 'Grass'), ('FIRE', 'Fire'), ('POISON', 'Poison'), ('WATER', 'Water'), ('NORMAL', 'Normal'), ('ELECTRIC', 'Electric'), ('ICE', 'Ice'), ('FIGHTING', 'Fighting'), ('GROUND', 'Ground'), ('FLYING', 'Flying'), ('PSYCHIC', 'Psychic'), ('BUG', 'Bug'), ('ROCK', 'Rock'), ('GHOST', 'Ghost'), ('DARK', 'Dark'), ('DRAGON', 'Dragon'), ('STEEL', 'Steel'), ('FAIRY', 'Fairy')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type2',
            field=models.CharField(blank=True, choices=[('GRASS', 'Grass'), ('FIRE', 'Fire'), ('POISON', 'Poison'), ('WATER', 'Water'), ('NORMAL', 'Normal'), ('ELECTRIC', 'Electric'), ('ICE', 'Ice'), ('FIGHTING', 'Fighting'), ('GROUND', 'Ground'), ('FLYING', 'Flying'), ('PSYCHIC', 'Psychic'), ('BUG', 'Bug'), ('ROCK', 'Rock'), ('GHOST', 'Ghost'), ('DARK', 'Dark'), ('DRAGON', 'Dragon'), ('STEEL', 'Steel'), ('FAIRY', 'Fairy')], max_length=10, null=True),
        ),
    ]
